#!/bin/bash
# Author : buwailee
# Script follows here:
aplatex -synctex=1 manifold > /dev/null
echo "1 o.k."
zhmakeindex -q manifold.idx >/dev/null
aplatex -synctex=1 manifold > /dev/null
echo "2 o.k."
rm *.dvi *.ilg *.out