#!/bin/bash
# Author : buwailee
# Script follows here:
xelatex coloredmain.tex > /dev/null
echo "1. o.k."
zhmakeindex -q -s main.mst coloredmain
for ((n=2;n<10;n++))
do
	xelatex coloredmain.tex > /dev/null
	echo $n". o.k."
done